[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[build]
  command = "NODE_OPTIONS=--max_old_space_size=4096 pnpm netlify:build"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- /"

  [[redirects]]
    from = "/reference/renderer-reference"
    to = "/en/reference/integrations-reference"

  [[redirects]]
    from = "/en/reference/renderer-reference"
    to = "/en/reference/integrations-reference"

  [[redirects]]
    from = "/en/core-concepts/component-hydration"
    to = "/en/concepts/islands"

  [[redirects]]
    from = "/core-concepts/component-hydration"
    to = "/en/concepts/islands"

  [[redirects]]
    from = "/en/getting-started/quick-start"
    to = "/en/install/auto"

  [[redirects]]
    from = "/docs/*"
    to = "/:splat"

  [[redirects]]
    from = "/:lang/docs/*"
    to = "/:lang/:splat"

  [[redirects]]
    from = "/:lang/core-concepts/partial-hydration"
    to = "/:lang/concepts/islands"
  
  [[redirects]]
    from = "/core-concepts/collections"
    to = "/en/guides/content-collections"
  
  [[redirects]]
    from = "/:lang/core-concepts/collections"
    to = "/:lang/guides/content-collections"

  [[redirects]]
    from = "/comparing-astro-vs-other-tools"
    to = "/en/guides/migrate-to-astro"

  [[redirects]]
    from = "/:lang/comparing-astro-vs-other-tools"
    to = "/:lang/guides/migrate-to-astro"

  [[redirects]]
    from = "/lighthouse/*"
    to = "/en/guides/migrate-to-astro"

  [[redirects]]
    from = "/:lang/guides/publish-to-npm"
    to = "/:lang/reference/publish-to-npm"

  [[redirects]]
    from = "/en/guides/debugging"
    to = "/en/guides/troubleshooting"

  [[redirects]]
    from = "/en/quick-start"
    to = "/en/installation"

  [[redirects]]
    from = "/en/concepts/mpa-vs-spa"
    to = "/en/concepts/why-astro"
    
  [[redirects]]
    from = "/:lang/deploy/:service"
    to = "/:lang/guides/deploy/:service"
    
  [[redirects]]
    from = "/:lang/guides/deploy/layer-zero"
    to = "/:lang/guides/deploy/edgio"

  [[redirects]]
    from = "/:lang/guides/client-side-routing"
    to = "/:lang/guides/view-transitions"

  [[redirects]]
    from = "/:lang/guides/assets"
    to = "/:lang/guides/images"

  [[redirects]]
    from = "/:lang/guides/integrations-guide/image"
    to = "/:lang/guides/images"

  [[redirects]]
    from = "/:lang/migration/0.21.0"
    to = "/:lang/guides/upgrade-to/v1"

  [[redirects]]
    from = "/:lang/migrate"
    to = "/:lang/guides/upgrade-to/v1"
    
  [[redirects]]
    from = "/"
    to = "/en/getting-started"

  [[redirects]]
    from = "/:lang/*"
    to = "/:lang/404/"
    status = 404
