[build]
  command = "NODE_OPTIONS=--max_old_space_size=4096 pnpm build"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- /"

  [[redirects]]
    from = "/reference/renderer-reference"
    to = "/en/reference/integrations-reference"

  [[redirects]]
    from = "/en/reference/renderer-reference"
    to = "/en/reference/integrations-reference"

  [[redirects]]
    from = "/en/core-concepts/component-hydration"
    to = "/en/concepts/islands"

  [[redirects]]
    from = "/core-concepts/component-hydration"
    to = "/en/concepts/islands"

  [[redirects]]
    from = "/en/getting-started/quick-start"
    to = "/en/install/auto"

  [[redirects]]
    from = "/docs/*"
    to = "/:splat"

  [[redirects]]
    from = "/:lang/docs/*"
    to = "/:lang/:splat"

  [[redirects]]
    from = "/:lang/core-concepts/partial-hydration"
    to = "/:lang/concepts/islands"

  [[redirects]]
    from = "/:lang/comparing-astro-vs-other-tools"
    to = "/:lang/guides/migrate-to-astro"

  [[redirects]]
    from = "/lighthouse/*"
    to = "/en/guides/migrate-to-astro"

  [[redirects]]
    from = "/:lang/guides/publish-to-npm"
    to = "/:lang/reference/publish-to-npm"

  [[redirects]]
    from = "/en/guides/debugging"
    to = "/en/guides/troubleshooting"

  [[redirects]]
    from = "/en/quick-start"
    to = "/en/installation"

  [[redirects]]
    from = "/:lang/deploy/:service"
    to = "/:lang/guides/deploy/:service"
    
  [[redirects]]
    from = "/:lang/guides/deploy/layer-zero"
    to = "/:lang/guides/deploy/edgio"

  [[redirects]]
    from = "/:lang/*"
    to = "/:lang/404/"
    status = 404
