[build]
  command = "pnpm build"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- /"

  [[redirects]]
    from = "/en/reference/renderer-reference"
    to = "/en/reference/integrations-reference"

  [[redirects]]
    from = "/en/core-concepts/component-hydration"
    to = "/en/concepts/islands"

  [[redirects]]
    from = "/core-concepts/component-hydration"
    to = "/en/concepts/islands"

  [[redirects]]
    from = "/en/getting-started/quick-start"
    to = "/en/install/auto"

  [[redirects]]
    from = "/docs/*"
    to = "/:splat"

  [[redirects]]
    from = "/:lang/docs/*"
    to = "/:lang/:splat"

  [[redirects]]
    from = "/:lang/core-concepts/partial-hydration"
    to = "/:lang/concepts/islands"

  [[redirects]]
    from = "/en/guides/debugging"
    to = "/en/guides/troubleshooting"

  [[redirects]]
    from = "/en/quick-start"
    to = "/en/installation"

  [[redirects]]
    from = "/:lang/deploy/:service"
    to = "/:lang/guides/deploy/:service"

  [[redirects]]
    from = "/:lang/*"
    to = "/:lang/404/"
    status = 404

  [[redirects]]
    from = "/:lang/guides/deploy/layer-zero"
    to = "/:lang/guides/deploy/edgio"

