[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version"

[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- /"

  [[redirects]]
    from = "/en/reference/renderer-reference"
    to = "/en/reference/integrations-reference"

  [[redirects]]
    from = "/en/core-concepts/component-hydration"
    to = "/en/core-concepts/partial-hydration"

  [[redirects]]
    from = "/en/quick-start"
    to = "/en/installation"

  [[redirects]]
    from = "/:lang/*"
    to = "/:lang/404/"
    status = 404
