blank_issues_enabled: false
contact_links:
  - name: Chat ğŸ‘¾
    url: https://astro.build/chat
    about: Our Discord server is active, come join us!
  - name: Support ğŸ’
    url: https://astro.build/chat
    about: 'This issue tracker is not for support questions. Join us on Discord for assistance!'
