blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Ideas for docs improvements or new content
    url: https://github.com/withastro/docs/discussions/new?category=ideas
    about: Share an idea for updating the docs with new or improved content.
  - name: ğŸ’ Support & Community
    url: https://astro.build/chat
    about: 'This issue tracker is not for support questions. Join us on Discord for assistance!'
  - name: ğŸ“š Contribute
    url: https://contribute.docs.astro.build
    about: 'Read our contributor docs.'
