name: Docs Contributors

on:
  schedule:
    - cron:  '0 3 * * SUN'
  workflow_dispatch:

jobs:
  contributors:
    name: docs_contributors
    if: ${{ github.repository_owner == 'withastro' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Update Docs Contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node --experimental-transform-types ./scripts/weekly-contributors.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          branch: ci/contributors
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
          add-paths: src/data/contributors.json
          commit-message: 'ci: update contributors'
          title: 'ci: update docs contributors'
          body: |
            This PR is auto-generated by a weekly GitHub action to update the list of contributors to the docs repository.
          labels: ci
