name: Docs Contributors

on:
  schedule:
    - cron:  '0 3 * * SUN'
  workflow_dispatch:

jobs:
  contributors:
    name: docs_contributors
    if: ${{ github.repository_owner == 'withastro' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Update Docs Contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node --experimental-transform-types ./scripts/weekly-contributors.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          branch: ci/contributors
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
          add-paths: src/data/contributors.json
          commit-message: 'ci: update contributors'
          title: 'ci: update docs contributors'
          body: |
            This PR is auto-generated by a weekly GitHub action to update the list of contributors to the docs repository.
          labels: ci
