name: Discord Notification on Push

on:
  push:
    branches: [main]

jobs:
  congrats:
    name: congratsbot
    if: ${{ github.repository_owner == 'withastro' && github.event.commits[0].message != '[ci] format' }}
    uses: withastro/automation/.github/workflows/congratsbot.yml@main
    with:
      EMOJIS: 'ğŸ‰,ğŸŠ,ğŸ§‘â€ğŸš€,ğŸ¥³,ğŸ™Œ,ğŸš€,<:notworsethanwhatwehadbefore:1020455379353751573>,<:houston_chef:1082696404780200067>,<:houston_uwu:1100481288143650977>'
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CONGRATS }}
