name: Lunaria

on:
  # Trigger the workflow every time a pull request is opened or synchronized at the target `main` branch
  pull_request_target:
    types: [opened, synchronize]
    branches: [main]

# Allow this job to clone the repository and comment on the pull request
permissions:
  contents: read
  pull-requests: write

jobs:
  lunaria-overview:
    name: Generate Lunaria Overview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Necessary for Lunaria to work properly
          # Makes the action clone the entire git history
          fetch-depth: 0

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Generate Lunaria Overview
        uses: yanthomasdev/lunaria-action@main
        with:
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
